#spring.application.name=user-soap-service
#
#
#server.port=8080
#
## H2 Database
#spring.datasource.url=jdbc:h2:mem:authdb
#spring.datasource.username=sanaa
#spring.datasource.password=0819
#
## JPA
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#
## H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
## App
#app.secret=MySecretKey123456
#
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/soap_db
#spring.datasource.username=postgres
#spring.datasource.password=0819
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.secret=${APP_SECRET}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect